WebApplication3/Controllers/SecondController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class SecondController : Controller
    {
        // GET: Second
        public ActionResult Index()
        {
            return View();
        }

     
        public ActionResult Succes()
        {
            return View();
        }

        public ActionResult java()
        {
            return View();
        }

        public ActionResult python()
        {
            return View();
        }

        public ActionResult C_sharp()
        {
            return View();
        }

        public ActionResult Nodejs()
        {
            return View();
        }

        public ActionResult Php()
        {
            return View();
        }

        public ActionResult Angular()
        {
            return View();
        }

        public ActionResult DB()
        {
            return View();
        }

        public ActionResult Fail()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Insert(WebApplication3.Models.Class1 li)
        {


            return View(li);
        }

        public ActionResult InsertData(WebApplication3.Models.Class1 li)
        {
            if (ModelState.IsValid)
            {
                WebApplication3.Models.Enterwhatever en = new Models.Enterwhatever();
                en.InsertData(li);
                //  ViewBag.name = li.nom;


                try
                {
                    if (ModelState.IsValid)
                    {
                        var senderEmail = new MailAddress("funfunny573@gmail.com", "Othmane.D");
                        var receiverEmail = new MailAddress(li.nom, "Receiver");
                        var passwordd = "dimaraja";
                        var body = "Votre Username est : " + li.login + "  et Votre Password est : " + li.pw;
                        var smtp = new SmtpClient
                        {
                            Host = "smtp.gmail.com",
                            Port = 587,
                            EnableSsl = true,
                            DeliveryMethod = SmtpDeliveryMethod.Network,
                            UseDefaultCredentials = false,
                            Credentials = new NetworkCredential(senderEmail.Address, passwordd)
                        };
                        using (var mess = new MailMessage(senderEmail, receiverEmail)
                        {
                            Subject = "Personal first Login Infos",
                            Body = body

                        })
                        {
                            smtp.Send(mess);
                        }
                        return View();
                    }
                }
                catch (Exception)
                {
                    ViewBag.Error = "Some Error";
                }




                @ViewBag.data = "Data inserted successfully !";
                return View("Insert");
            }
            else
            {
                return View("Insert");
            }



        }


        public ActionResult Loginn(WebApplication3.Models.Class1 li)
        {
            return View(li);

        }
        public ActionResult Loginsearch(WebApplication3.Models.Class1 li)
        {
            WebApplication3.Models.Search ss = new Models.Search();
            string pass = ss.searchLP(li);


            if (pass == li.pw)
            {

                return View("Succes");

            }
            @ViewBag.data = "invalide Login (Plz try again...)";
            return View("Fail");

        }





    }
}

WebApplication3/Views/Second/Angular.cshtml
@{
    ViewBag.Title = "Angular";
}

<link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">Angular</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/angular1.bmp alt="">
            <img class="img-responsive" src=../images/angular2.bmp alt="">
        </div>
        <div class="col-sm-6">
            <h3>What is Angular?</h3>
            <p class="main-text">
                Angular n'a pas de notion de "portée" ou de contrôleurs, au lieu de cela il utilise une hiérarchie de composants comme principale caractéristique architecturale4.<br><br>
                Angular a une syntaxe d'expression différente, en se concentrant sur les "[ ]" pour la liaison des propriétés, et de "( )" pour les liaisons des événements5<br><br>
                Modularité – beaucoup de fonctionnalités de base ont été déplacées vers des modules
                Angular recommande l'utilisation du langage TypeScript, créé par Microsoft, qui présente les caractéristiques suivantes:<br><br>
                le principe de classe, à la base de la Programmation Orientée Objet<br>
                le typage statique<br>
                les génériques<br>
                TypeScript est un sur-ensemble d'ECMAScript 6 (ES6), et est rétro-compatible avec ECMAScript 5 (c'est-à-dire: JavaScript). Angular comprend également les principes d'ES6 suivant :<br><br>
                les fonctions anonymes<br>
                les itérateurs<br>
                boucles for-of<br>
                générateurs dans le style du langage Python<br>
                La réflexion<br>
                Le chargement dynamique<br />
                Compilation asynchrone des modèles<br>
                Itératif rappels fournis par RxJS. RxJS limites de l'état de visibilité et de débogage, mais ces problèmes peuvent être résolus avec réactif add-ons comme ngReact ou ngrx.<br><br>
            </p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>

WebApplication3/Views/Second/C_sharp.cshtml
@{
    ViewBag.Title = "C#";
}

<link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">C#</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/c1.bmp alt="">
            <img class="img-responsive" src=../images/c2.bmp alt="">
        </div>
        <div class="col-sm-6">
            <h3>What is C#?</h3>
            <p class="main-text">
                C# est un langage de programmation orientée objet, commercialisé par Microsoft depuis 20023 et destiné à développer sur la plateforme Microsoft .NET.

                Il est dérivé du C++ et très proche du Java dont il reprend la syntaxe générale ainsi que les concepts, y ajoutant des notions telles que la surcharge des opérateurs, les indexeurs et les délégués. Il est utilisé notamment pour développer des applications web sur la plateforme ASP.NET. <br><br>C# est un langage de programmation orientée objet, fortement typé, dérivé de C et de C++, ressemblant au langage Java3. Il est utilisé pour développer des applications web, ainsi que des applications de bureau, des services web, des commandes, des widgets ou des bibliothèques de classes3. En C#, une application est un lot de classes où une des classes comporte une méthode Main, comme cela se fait en Java3.

                C# est destiné à développer sur la plateforme .NET, une pile technologique créée par Microsoft pour succéder à COM.

                Les exécutables en C# sont subdivisés en assemblies, en namespaces, en classes et en membres de classe4. Un assembly est la forme compilée, qui peut être un programme (un exécutable) ou une bibliothèque de classes (une dll). Un assembly contient le code exécutable en MSIL, ainsi que les symboles. Le code MSIL est traduit en langage machine au moment de l'exécution par la fonction just-in-time de la plateforme .NET.<br><br>Currently on a mission of reducing the costs of space travel by a factor of 100 and colonization of Mars, Elon Musk is the 21st-century inventor. He’s also been working on  Hyperloop , a high-speed, solar-powered transportation system, capable of transporting from Los Angeles to San Francisco in 30 minutes.<br><br>C# est un langage dérivé du C++, il apporte un typage sûr, ainsi que les possibilités d'encapsulation, d'héritage et de polymorphisme des langages orientés objet3. En C# tous les types sont des objets3. Le langage comporte un ramasse-miettes et un système de gestion d'exceptions3.

                Le typage sûr signifie notamment que les opérations suivantes sont refusées : utilisation de variable non initialisée, tentative d'accéder au-delà des limites d'un tableau, conversions de type dont les résultats ne sont pas prévisibles, dépassement des limites lors d'opérations arithmétiques<br><br>
            </p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>

WebApplication3/Views/Second/DB.cshtml
@{
    ViewBag.Title = "DB";
}

<link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">Data bases</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/db1.bmp alt="A young Elon Musk sitting in front of a computer">
            <img class="img-responsive" src=../images/db2.bmp alt="Elon Musk answering a question">
        </div>
        <div class="col-sm-6">
            <h3>What is data bases?</h3>
            <p class="main-text">
                Une base de données (en anglais database), permet de stocker et de retrouver des données brutes ou de l'information, souvent en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Leurs données peuvent être stockées sous une forme très structurées (base de données relationnelles par exemple), ou bien sous la forme de données brutes peu structurées voire déstructurées (base de données NoSQL Redis par exemple). Une base de données peut être localisée dans un même lieu et sur un même support informatisé, ou réparties sur plusieurs machines à plusieurs endroits.

                La base de données est au centre des dispositifs informatiques de collecte, mise en forme, stockage et utilisation d'informations. Le dispositif comporte un système de gestion de base de données (abréviation : SGBD) : un logiciel moteur qui manipule la base de données et dirige l'accès à son contenu. De tels dispositifs comportent également des logiciels applicatifs, et un ensemble de règles relatives à l'accès et l'utilisation des informations2.

                La manipulation de données est une des utilisations les plus courantes des ordinateurs. Les bases de données sont par exemple utilisées dans les secteurs de la finance, des assurances, des écoles, de l'épidémiologie, de l'administration publique (notamment les statistiques) et des médias.

                Lorsque plusieurs objets nommés « bases de données » sont constitués sous forme de collection, on parle alors d'une banque de données. <br /><br />
                Une base de données est un « conteneur » stockant des données2 telles que des chiffres, des dates ou des mots, pouvant être retraités par des moyens informatiques pour produire une information ; par exemple, des chiffres et des noms assemblés et triés pour former un annuaire. Les retraitements sont typiquement une combinaison d'opérations de recherches, de choix, de tri, de regroupement, et de concaténation3.

                C'est la pièce centrale d'un système d'information ou d'un système de base de données (ou base de données tout court), qui régit la collecte, le stockage, le retraitement et l'utilisation de données. Ce dispositif comporte souvent un logiciel moteur (cf. paragraphe suivant), des logiciels applicatifs, et un ensemble de règles relatives à l'accès et l'utilisation des informations<br><br>
            </p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>

WebApplication3/Views/Second/Fail.cshtml
@{
    ViewBag.Title = "Fail";
}
    <link rel="stylesheet" href="~/style/test.css" type="text/css" />
    <h2>FAIL : invalide Login (Plz try again...)</h2>

WebApplication3/Views/Second/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="~/style/Styleindex.css" type="text/css" />
<div id="divi">
    <h1>< <span class="blink">_</span> /></h1>
</div>
<br />
<br />

<div id="para">
    <div><h1><strong>Welcome to my learning website</strong></h1></div>

    <div><h1><u>Sign up</u> and <u> login </u>to be a great developper !</h1></div>
</div>

<br />
<br />




<!-- Footer -->
<footer id="foot" class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        © 2020 Copyright:
        <a href="https://localhost:44393/Second/Index"> Learning_dendane.com</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

WebApplication3/Views/Second/Insert.cshtml
@model WebApplication3.Models.Class1
@{
    ViewBag.Title = "Insert";
}

<h2>Sign up</h2>

@using (Html.BeginForm("InsertData", "Second"))
{
    @Html.ValidationSummary(true)
    {
        <div class="container">

            <form class="well form-horizontal" action=" " method="post" id="contact_form">
                <fieldset>



                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label">E-Mail</label>
                        <div class="col-md-4 inputGroupContainer">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>

                                @Html.TextBoxFor(model => model.nom, new { placeholder = "E-Mail Address", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <br />

                    <!-- Text input-->

                    <div class="form-group">
                         <label class="col-md-4 control-label">Last Name</label>
                        <div class="col-md-4 inputGroupContainer">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                @Html.TextBoxFor(model => model.prenom, new { placeholder = "Last name", @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <br />



                    <div class="form-group">
                        <label class="col-md-4 control-label">Age</label>
                        <div class="col-md-4 inputGroupContainer">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                @Html.TextBoxFor(model => model.age, new { placeholder = "Age", @class = "form-control" })
                            </div>
                        </div>
                    </div>


                    <br />
                    <br />



                    <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label"></label>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-primary" value="Sign-Up">Send <span class="glyphicon glyphicon-send"></span></button>
                        </div>
                    </div>

                </fieldset>
            </form>
        </div>
        <!-- /.container -->

    }
}

WebApplication3/Views/Second/InsertData.cshtml
@{
    ViewBag.Title = "Learning";
}
   

WebApplication3/Views/Second/Login.cshtml
@model WebApplication3.Models.Class1
@{
    ViewBag.Title = "Login";
}
<link rel="stylesheet" href="~/style/styleLogin.css" type="text/css" />
<h2>Login</h2>

@using (Html.BeginForm("Loginsearch", "Second"))
{
    @Html.ValidationSummary(true)
    {

        <body class="align">

    <div class="grid">

        <form action="https://httpbin.org/post" method="POST" class="form login">

            <div class="form__field">
                <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Username</span></label>
                @Html.TextBoxFor(model => model.login, new { id="login__username", placeholder = "Login", @class = "form-control" })
            </div>

            <div class="form__field">
                <label for="login__password"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use></svg><span class="hidden">Password</span></label>
                
                @Html.TextBoxFor(model => model.pw, new {id="login__password", placeholder = "Paswword", @class = "form-control" })
            </div>

            <div class="form__field">
                <input id="button" type="submit" value="Sign In">
            </div>

        </form>

        <p class="text--center">Not a member? <a href="https://localhost:44393/Second/Insert">Sign up now</a> <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="assets/images/icons.svg#arrow-right"></use></svg></p>

    </div>

    <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z" /></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z" /></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z" /></symbol></svg>

</body>


        


        @ViewBag.data

    }
}

WebApplication3/Views/Second/Nodejs.cshtml
@{
    ViewBag.Title = "NodeJs";
}

<link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">NodeJs</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/node1.bmp alt="">
            <img class="img-responsive" src=../images/node2.bmp alt="">
        </div>
        <div class="col-sm-6">
            <h3>What is NodeJs?</h3>
            <p class="main-text">
                Node.js est une plateforme logicielle libre en JavaScript orientée vers les applications réseau événementielles hautement concurrentes qui doivent pouvoir monter en charge.

                Elle utilise la machine virtuelle V8, la librairie libuv pour sa boucle d'évènements, et implémente sous licence MIT les spécifications CommonJS.

                Parmi les modules natifs de Node.js, on retrouve http qui permet le développement de serveur HTTP. Il est donc possible de se passer de serveurs web tels que Nginx ou Apache lors du déploiement de sites et d'applications web développés avec Node.js.

                Concrètement, Node.js est un environnement bas niveau permettant l’exécution de JavaScript côté serveur.<br><br>Node.js a été créé par Ryan Dahl en 2009. Son développement et sa maintenance sont effectués par l'entreprise Joyent (en)13. Dahl a eu l'idée de créer Node.js après avoir observé la barre de progression d'un chargement de fichier sous Flickr : le navigateur ne savait pas quel pourcentage du fichier était chargé et devait adresser une requête au serveur web. Dahl voulait développer une méthode plus simple14. Le serveur web Mongrel de Ruby a été l'autre source d'inspiration pour Dahl15. Dahl avait échoué dans plusieurs projets en C, Lua et Haskell, mais, quand le moteur V8 fut diffusé, il commença à s'intéresser à JavaScript16. Même si son idée d'origine était d'utiliser des entrées et sorties non bloquantes, il en reviendra un peu dans son module système car cela provoquait des problèmes de chargement de bibliothèques externes17.

                Node.js est utilisé au cœur du système d'exploitation Palm webOS.<br><br>Depuis janvier 2017, la fondation Node.js a pour projet de créer une certification professionnelle, la NCD24 (Nodejs Certified Developer). Cette certification est proposée en partenariat avec la Fondation Linux et est actuellement disponible en accès anticipé.<br><br>
            </p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>

WebApplication3/Views/Second/Php.cshtml
@{
    ViewBag.Title = "Php";
}

<link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">Php</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/php1.bmp alt="A young Elon Musk sitting in front of a computer">
            <img class="img-responsive" src=../images/php2.bmp alt="Elon Musk answering a question">
        </div>
        <div class="col-sm-6">
            <h3>What is Php?</h3>
            <p class="main-text">
                PHP est un langage de script utilisé le plus souvent côté serveur : dans cette architecture, le serveur interprète le code PHP des pages web demandées et génère du code (HTML, XHTML, CSS par exemple) et des données (JPEG, GIF, PNG par exemple) pouvant être interprétés et rendus par un Navigateur web. PHP peut également générer d'autres formats comme le WML, le SVG et le PDF.
                <br /><br />
                Il a été conçu pour permettre la création d'applications dynamiques, le plus souvent développées pour le Web. PHP est le plus souvent couplé à un serveur Apache bien qu'il puisse être installé sur la plupart des serveurs HTTP tels que IIS ou nginx. Ce couplage permet de récupérer des informations issues d'une base de données, d'un système de fichiers (contenu de fichiers et de l'arborescence) ou plus simplement des données envoyées par le navigateur afin d'être interprétées ou stockées pour une utilisation ultérieure.
                <br /><br />
                C'est un langage peu typé et souple et donc facile à apprendre par un débutant mais, de ce fait, des failles de sécurité peuvent rapidement apparaître dans les applications. Pragmatique, PHP ne s'encombre pas de théorie et a tendance à choisir le chemin le plus direct. Néanmoins, le nom des fonctions (ainsi que le passage des arguments) ne respecte pas toujours une logique uniforme, ce qui peut être préjudiciable à l'apprentissage.
            </p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>

WebApplication3/Views/Second/Succes.cshtml
@{
    ViewBag.Title = "Learning";
}
<link rel="stylesheet" href="~/style/Stylepage.css" type="text/css" />
<h1><span>Programmation</span> Languages learning</h1>

<!-- Flex Container -->
<div id="container">

    <a id="button-1" class="button" href="https://localhost:44393/Second/java">Java!<img id="arrow-hover" src="https://github.com/atloomer/atloomer.github.io/blob/master/img/iconmonstr-paper-plane-1-120.png?raw=true" /></a>

    <div class="button" id="button-2">
        <div id="slide"></div>
        <a href="https://localhost:44393/Second/python">Python!</a>
    </div>

    <div class="button" id="button-3">
        <div id="circle"></div>
        <a href="https://localhost:44393/Second/C_sharp">C#!</a>
    </div>

    <div class="button" id="button-4">
        <div id="underline"></div>
        <a href="https://localhost:44393/Second/Nodejs">NodeJs!</a>
    </div>

    <div class="button" id="button-5">
        <div id="translate"></div>
        <a href="https://localhost:44393/Second/Php">Php!</a>
    </div>

    <div class="button" id="button-6">
        <div id="spin"></div>
        <a href="https://localhost:44393/Second/Angular">Angular!</a>
    </div>

    <div class="button" id="button-2">
        <div id="slide"><img src="https://github.com/atloomer/atloomer.github.io/blob/master/img/iconmonstr-arrow-48-240.png?raw=true" alt="" /></div>
        <a href="https://localhost:44393/Second/DB">Data bases!</a>
    </div>


    <!-- End Container -->
</div>

WebApplication3/Views/Second/java.cshtml
@{
    ViewBag.Title = "Java";
}
    <link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">Java</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/java1.bmp alt="A young Elon Musk sitting in front of a computer">
            <img class="img-responsive" src=../images/java2.bmp alt="Elon Musk answering a question">
        </div>
        <div class="col-sm-6">
            <h3>What is Java?</h3>
            <p class="main-text">Le langage Java reprend en grande partie la syntaxe du langage C++. Néanmoins, Java a été épuré des concepts les plus subtils du C++ et à la fois les plus déroutants, tels que les pointeurs et références, ou l’héritage multiple contourné par l’implémentation des interfaces. De même, depuis la version 8, l'arrivée des interfaces fonctionnelles introduit l'héritage multiple (sans la gestion des attributs) avec ses avantages et inconvénients tels que l'héritage en diamant. Les concepteurs ont privilégié l’approche orientée objet de sorte qu’en Java, tout est objet à l’exception des types primitifs (nombres entiers, nombres à virgule flottante, etc.) qui ont cependant leurs variantes qui héritent de l'objet Object (Integer, Float, ...).<br><br>Java permet de développer des applications client-serveur. Côté client, les applets sont à l’origine de la notoriété du langage. C’est surtout côté serveur que Java s’est imposé dans le milieu de l’entreprise grâce aux servlets, le pendant serveur des applets, et plus récemment les JSP (JavaServer Pages) qui peuvent se substituer à PHP, ASP et ASP.NET. <br><br></p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>

WebApplication3/Views/Second/python.cshtml
@{
    ViewBag.Title = "Python";
}

<link rel="stylesheet" href="~/style/Stylelanguage.css" type="text/css" />
<h1 class="text-center">Python</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-responsive" src=../images/py1.bmp alt="">
            <img class="img-responsive" src=../images/py2.bmp alt="">
        </div>
        <div class="col-sm-6">
            <h3>What is Python?</h3>
            <p class="main-text">
                Le langage Python est placé sous une licence libre proche de la licence BSD7 et fonctionne sur la plupart des plates-formes informatiques, des smartphones aux ordinateurs centraux8, de Windows à Unix avec notamment GNU/Linux en passant par macOS, ou encore Android, iOS, et peut aussi être traduit en Java ou .NET. Il est conçu pour optimiser la productivité des programmeurs en offrant des outils de haut niveau et une syntaxe simple à utiliser.<br><br>

                Python est un langage de programmation qui peut s'utiliser dans de nombreux contextes et s'adapter à tout type d'utilisation grâce à des bibliothèques spécialisées. Il est cependant particulièrement utilisé comme langage de script pour automatiser des tâches simples mais fastidieuses, comme un script qui récupérerait la météo sur Internet ou qui s'intégrerait dans un logiciel de conception assistée par ordinateur afin d'automatiser certains enchaînements d'actions répétitives (voir la section Adoption). On l'utilise également comme langage de développement de prototype lorsqu'on a besoin d'une application fonctionnelle avant de l'optimiser avec un langage de plus bas niveau. Il est particulièrement répandu dans le monde scientifique, et possède de nombreuses bibliothèques optimisées destinées au calcul numérique.<br><br>
            </p>
            <a href="https://en.wikipedia.org/wiki/Elon_Musk">Learn More</a>
        </div>
    </div>
</div>